// Datos de las figuras. Para agregar una nueva, copiá un objeto y editalo.
// points: de menor a mayor. keywords: tal cual querés buscarlas.
const FIGURES = [
  {"name": "Angel", "img": "Images/Minis/dofp005.jpg", "alt": "Angel dofp005", "keywords": ["Celebrity", "Champions", "Defenders", "X-Factor", "X-Men"], "points": [74]},
  {"name": "Apocalypse", "img": "Images/Minis/xmrf062.jpg", "alt": "Apocalypse xmrf062", "keywords": ["Horsemen", "X-Men", "Armor", "Future", "Past", "Ruler"], "points": [75, 125]},
  {"name": "Batman", "img": "Images/Minis/dkr100.jpg", "alt": "Batman dkr100", "keywords": ["Detective", "Gotham City", "Martial Artist"], "points": [105]},
  {"name": "Beast", "img": "Images/Minis/wcr005.jpg", "alt": "Beast wcr005", "keywords": ["Avengers", "Defenders", "Jean Grey School for Higher Learning", "X-Men", "Animal", "Scientist"], "points": [40, 70]},
  {"name": "Black Bolt", "img": "Images/Minis/affe016.jpg", "alt": "Black Bolt affe016", "keywords": ["Illuminati", "Inhumans", "Skrulls", "Ruler", "Spy", "Warrior"], "points": [75]},
  {"name": "Blackheart", "img": "Images/Minis/xmrf055.jpg", "alt": "Blackheart xmrf055", "keywords": ["Hellfire Club", "Deity", "Monster", "Mystical", "Ruler"], "points": [75, 125]},
  {"name": "Brawn", "img": "Images/Minis/affe022.jpg", "alt": "Brawn affe022", "keywords": ["Agents of Atlas", "Avengers", "Champions", "Fantastic Four", "Illuminati", "S.H.I.E.L.D.", "Monster", "Scientist"], "points": [75]},
  {"name": "Broo", "img": "Images/Minis/xmrf030.jpg", "alt": "Broo xmrf030", "keywords": ["Brood", "Jean Grey School for Higher Learning", "Wakanda", "X-Men", "Animal", "Monster"], "points": [40]},
  {"name": "Cable", "img": "Images/Minis/gx102.jpg", "alt": "Cable gx102", "keywords": ["Armor", "Future", "New Mutants", "Ruler", "Six Pack", "Soldier", "X-Force", "X-Men"], "points": [140]},
  {"name": "Callisto", "img": "Images/Minis/xmrf029.jpg", "alt": "Callisto xmrf029", "keywords": ["Excalibur", "Hellfire Club", "Morlocks", "Ruler"], "points": [35]},
  {"name": "Captain Britain", "img": "Images/Minis/hx053.jpg", "alt": "Captain Britain hx053", "keywords": ["Excalibur", "Martial Artist", "Mystical", "X-Men"], "points": [30, 80]},
  {"name": "Captain Marvel", "img": "Images/Minis/affe004.jpg", "alt": "Captain Marvel affe004", "keywords": ["Avengers", "Cosmic", "Kree", "Soldier"], "points": [70, 130]},
  {"name": "Colossus", "img": "Images/Minis/affe040.jpg", "alt": "Colossus affe040", "keywords": ["Jean Grey School for Higher Learning", "X-Men", "Armor", "Future", "Mystical", "Ruler"], "points": [125]},
  {"name": "Corvus Glaive", "img": "Images/Minis/gotg049.jpg", "alt": "Corvus Glaive gotg049", "keywords": ["Black Order", "Minions of Thanos", "Warrior"], "points": [100]},
  {"name": "Daredevil", "img": "Images/Minis/affe030.jpg", "alt": "Daredevil affe030", "keywords": ["Avengers", "Defenders", "Heroes For Hire", "Marvel Knights", "Spider-Man Family", "Martial Artist"], "points": [25, 75]},
  {"name": "Dario Agger", "img": "Images/Minis/caav022.jpg", "alt": "Dario Agger caav022", "keywords": ["A.I.M.", "Hydra", "Monster", "Mystical", "Politician", "Ruler"], "points": [50, 75]},
  {"name": "Deadpool", "img": "Images/Minis/affe044.jpg", "alt": "Deadpool affe044", "keywords": ["Deadpool Corps", "Assassin", "Monster", "Ruler"], "points": [40, 75]},
  {"name": "Diablo", "img": "Images/Minis/ffff047a.jpg", "alt": "Diablo ffff047", "keywords": ["Fantastic Four", "Mystical", "Past", "Scientist"], "points": [60, 70]},
  {"name": "Domino", "img": "Images/Minis/hx012.jpg", "alt": "Domino hx012", "keywords": ["X-Force", "X-Men", "Assassin", "Spy"], "points": [60]},
  {"name": "Doom 2099, Revolutionary", "img": "Images/Minis/f4060.jpg", "alt": "Doom 2099, Revolutionary f4060", "keywords": ["Latveria", "S.H.I.E.L.D.", "Armor", "Future", "Mystical", "Politician", "Ruler", "Scientist"], "points": [125]},
  {"name": "Dormammu", "img": "Images/Minis/wkM15-010.jpg", "alt": "Dormammu wkM15010", "keywords": ["Deity", "Mystical", "Ruler"], "points": [250, 300]},
  {"name": "Ebony Maw", "img": "Images/Minis/abpi067.jpg", "alt": "Ebony Maw abpi067", "keywords": ["Black Order", "Cabal", "Minions of Thanos", "Cosmic"], "points": [100]},
  {"name": "Emma Frost", "img": "Images/Minis/xmrf053.jpg", "alt": "Emma Frost xmrf053", "keywords": ["Hellfire Club", "Hellions", "Marauders", "Quiet Council", "Utopia", "X-Men", "Politician"], "points": [75, 125]},
  {"name": "Eric the Red", "img": "Images/Minis/xmrf018.jpg", "alt": "Eric the Red xmrf018", "keywords": ["Shi'ar", "Armor", "Soldier", "Warrior"], "points": [35]},
  {"name": "Etrigan the Demon", "img": "Images/Minis/fl045.jpg", "alt": "Etrigan the Demon fl045", "keywords": ["Demon Knights", "Monster", "Mystical", "Past", "Shadowpact", "Warrior"], "points": [135]},
  {"name": "Exodus", "img": "Images/Minis/xmrf039.jpg", "alt": "Exodus xmrf039", "keywords": ["Acolytes", "Brotherhood of Mutants", "Marauders", "Quiet Council", "X-Men", "Herald", "Past"], "points": [95]},
  {"name": "Flash Thompson", "img": "Images/Minis/svc028.jpg", "alt": "Flash Thompson svc028", "keywords": ["Avengers", "Codex", "Guardians of the Galaxy", "S.H.I.E.L.D.", "Spider-Man Family", "Soldier"], "points": [35]},
  {"name": "Forge", "img": "Images/Minis/hx002.jpg", "alt": "Forge hx002", "keywords": ["X-Factor", "X-Force", "X-Men", "Mystical", "Scientist", "Soldier"], "points": [60]},
  {"name": "Gambit", "img": "Images/Minis/wcr007.jpg", "alt": "Gambit wcr007", "keywords": ["Jean Grey School for Higher Learning", "Marauders", "X-Men", "Spy"], "points": [50, 80]},
  {"name": "Ghost Rider", "img": "Images/Minis/f4026.jpg", "alt": "Ghost Rider f4026", "keywords": ["Fantastic Four", "S.H.I.E.L.D.", "Mystical"], "points": [40, 80]},
  {"name": "Golden Oldie", "img": "Images/Minis/affe018.jpg", "alt": "Golden Oldie affe018", "keywords": ["Spider-Man Family", "Cosmic", "Herald"], "points": [45]},
  {"name": "Golden Oldie", "img": "Images/Minis/affe018.jpg", "alt": "Golden Oldie affe018", "keywords": ["Spider-Man Family", "Cosmic", "Herald"], "points": [45]},
  {"name": "Gorr the God Butcher", "img": "Images/Minis/gotg042.jpg", "alt": "Gorr the God Butcher gotg042", "keywords": ["Assassin", "Cosmic", "Deity"], "points": [170]},
  {"name": "Gwen Stacy", "img": "Images/Minis/svc027.jpg", "alt": "Gwen Stacy svc027", "keywords": ["Spider-Man Family", "Celebrity"], "points": [25]},
  {"name": "Harley Quinn", "img": "Images/Minis/ww80024.jpg", "alt": "Harley Quinn ww80024", "keywords": ["Amazon", "Arkham Asylum", "Gotham City Sirens", "Gotham City Underworld", "Scientist"], "points": [25, 50]},
  {"name": "Hela", "img": "Images/Minis/fi102.jpg", "alt": "Hela fi102", "keywords": ["Asgardian", "Deity", "Mystical", "Ruler"], "points": [160]},
  {"name": "Hellfire Club Guard", "img": "Images/Minis/xmrf006.jpg", "alt": "Hellfire Club Guard xmrf006", "keywords": ["Hellfire Club", "Soldier"], "points": [25]},
  {"name": "Hellfire Club Guard", "img": "Images/Minis/xmrf006.jpg", "alt": "Hellfire Club Guard xmrf006", "keywords": ["Hellfire Club", "Soldier"], "points": [25]},
  {"name": "Hellfire Club Guard", "img": "Images/Minis/xmrf006.jpg", "alt": "Hellfire Club Guard xmrf006", "keywords": ["Hellfire Club", "Soldier"], "points": [25]},
  {"name": "Hellfire Club Guard", "img": "Images/Minis/xmrf006.jpg", "alt": "Hellfire Club Guard xmrf006", "keywords": ["Hellfire Club", "Soldier"], "points": [25]},
  {"name": "Iron Man", "img": "Images/Minis/svc002.jpg", "alt": "Iron Man svc002", "keywords": ["Spider-Man Family", "Stark Industries", "Armor", "Celebrity"], "points": [60]},
  {"name": "J. Jonah Jameson", "img": "Images/Minis/sfsm006.jpg", "alt": "J. Jonah Jameson sfs0006", "keywords": ["Politician", "Reporter"], "points": [30]},
  {"name": "Jubilee", "img": "Images/Minis/affe034.jpg", "alt": "Jubilee affe034", "keywords": ["Excalibur", "Generation X", "X-Men", "Mystical"], "points": [35, 75]},
  {"name": "Kaine", "img": "Images/Minis/asm036.jpg", "alt": "Kaine xmrf036", "keywords": ["Brute", "Spider-Man Family"], "points": [117]},
  {"name": "Kid Gladiator", "img": "Images/Minis/xmrf036.jpg", "alt": "Kid Gladiator xmrf036", "keywords": ["Imperial Guard", "Jean Grey School for Higher Learning", "Shi'ar", "X-Men", "Cosmic"], "points": [75]},
  {"name": "Kree Soldier", "img": "Images/Minis/affe003.jpg", "alt": "Kree Soldier affe003", "keywords": ["Kree", "Soldier"], "points": [20]},
  {"name": "Kree Soldier", "img": "Images/Minis/affe003.jpg", "alt": "Kree Soldier affe003", "keywords": ["Kree", "Soldier"], "points": [20]},
  {"name": "Kristoff", "img": "Images/Minis/ffff041.jpg", "alt": "Kristoff ffff041", "keywords": ["Latveria", "Armor", "Mystical", "Ruler", "Scientist"], "points": [40, 75]},
  {"name": "Lilandra Neramani", "img": "Images/Minis/xmrf035.jpg", "alt": "Lilandra Neramani xmrf035", "keywords": ["Imperial Guard", "Shi'ar", "Starjammers", "X-Men", "Ruler"], "points": [50]},
  {"name": "Loki", "img": "Images/Minis/affe026.jpg", "alt": "Loki affe026", "keywords": ["Asgardian", "Guardians of the Galaxy", "Young Avengers", "Deity", "Mystical"], "points": [60]},
  {"name": "Loki", "img": "Images/Minis/affe026.jpg", "alt": "Loki affe026", "keywords": ["Asgardian", "Guardians of the Galaxy", "Young Avengers", "Deity", "Mystical"], "points": [60]},
  {"name": "Loki", "img": "Images/Minis/affe026.jpg", "alt": "Loki affe026", "keywords": ["Asgardian", "Guardians of the Galaxy", "Young Avengers", "Deity", "Mystical"], "points": [60]},
  {"name": "Loki", "img": "Images/Minis/affe026.jpg", "alt": "Loki affe026", "keywords": ["Asgardian", "Guardians of the Galaxy", "Young Avengers", "Deity", "Mystical"], "points": [60]},
  {"name": "Magik", "img": "Images/Minis/dcxm007.jpg", "alt": "Magik dcxm007", "keywords": ["New Mutants", "Utopia", "X-Men", "Monster", "Mystical"], "points": [50]},
  {"name": "Magneto", "img": "Images/Minis/xxs023b.jpg", "alt": "Magneto xxs023b", "keywords": ["Brotherhood of Mutants", "Hellfire Club", "New Mutants"], "points": [75]},
  {"name": "Magneto", "img": "Images/Minis/xmrf027.jpg", "alt": "Magneto xmrf027", "keywords": ["Acolytes", "Brotherhood of Mutants", "Hellfire Club"], "points": [40]},
  {"name": "Magneto", "img": "Images/Minis/uxm029.jpg", "alt": "Magneto uxm029", "keywords": ["Brotherhood of Mutants", "Detective"], "points": [50]},
  {"name": "Magneto, Realist", "img": "Images/Minis/xxs050.jpg", "alt": "Magneto, Realist xxs050", "keywords": ["Acolytes", "Brotherhood of Mutants"], "points": [100]},
  {"name": "Mandarin", "img": "Images/Minis/caav061.jpg", "alt": "Mandarin caav061", "keywords": ["Mandarin's Minions", "The Hand", "Martial Artist", "Mystical", "Ruler", "Scientist"], "points": [70]},
  {"name": "Marquis of Death", "img": "Images/Minis/ffff061.jpg", "alt": "Marquis of Death ffff061", "keywords": ["Cosmic"], "points": [60, 200]},
  {"name": "Mary Jane Watson", "img": "Images/Minis/svc014.jpg", "alt": "Mary Jane Watson svc014", "keywords": ["Spider-Man Family", "Stark Industries", "Celebrity"], "points": [15]},
  {"name": "Mary Jane", "img": "Images/Minis/sfsm019.jpg", "alt": "Mary Jane sfsm019", "keywords": ["Spider-Man Family", "Celebrity"], "points": [25]},
  {"name": "Mary Jane", "img": "Images/Minis/sfsm019.jpg", "alt": "Mary Jane sfsm019", "keywords": ["Spider-Man Family", "Celebrity"], "points": [25]},
  {"name": "Miles and Gwen", "img": "Images/Minis/wkMP19-007.jpg", "alt": "Miles and Gwen wkMP19007", "keywords": ["Champions", "Secret Warriors", "Spider-Man Family"], "points": [100]},
  {"name": "Minotaur", "img": "Images/Minis/caav027.jpg", "alt": "Minotaur caav027", "keywords": ["A.I.M.", "Hydra", "Animal", "Brute", "Monster", "Mystical", "Ruler"], "points": [50, 125]},
  {"name": "Mister Sinister", "img": "Images/Minis/hx031.jpg", "alt": "Mister Sinister hx031", "keywords": ["Hellions", "Marauders", "Quiet Council", "X-Men", "Ruler", "Scientist"], "points": [85]},
  {"name": "Mister Sinister, Rogue Geneticist", "img": "Images/Minis/xdps043a.jpg", "alt": "Mister Sinister, Rogue Geneticist xdps043a", "keywords": ["Marauders", "Savage Land", "Past", "Scientist"], "points": [100]},
  {"name": "Moira MacTaggart", "img": "Images/Minis/xxs007a.jpg", "alt": "Moira MacTaggart xxs007a", "keywords": ["X-Men", "Scientist"], "points": [25]},
  {"name": "Molecule Man", "img": "Images/Minis/ffff044.jpg", "alt": "Molecule Man ffff044", "keywords": ["Battleworld: Other", "Latveria", "Cosmic", "Scientist"], "points": [30, 100]},
  {"name": "Morgan Spurlock", "img": "Images/Minis/sdcc003.jpg", "alt": "Morgan Spurlock sdcc003", "keywords": ["Detective", "Reporter"], "points": [66]},
  {"name": "Morgan Spurlock", "img": "Images/Minis/sdcc003.jpg", "alt": "Morgan Spurlock sdcc003", "keywords": ["Detective", "Reporter"], "points": [66]},
  {"name": "Morgan Spurlock", "img": "Images/Minis/sdcc003.jpg", "alt": "Morgan Spurlock sdcc003", "keywords": ["Detective", "Reporter"], "points": [66]},
  {"name": "Multiple Man", "img": "Images/Minis/xmrf007.jpg", "alt": "Multiple Man xmrf007", "keywords": ["Hydra", "Maggia", "S.H.I.E.L.D.", "X-Factor", "X-Men", "Detective", "Spy"], "points": [40, 10]},
  {"name": "Multiple Man", "img": "Images/Minis/xmrf007.jpg", "alt": "Multiple Man xmrf007", "keywords": ["Hydra", "Maggia", "S.H.I.E.L.D.", "X-Factor", "X-Men", "Detective", "Spy"], "points": [40, 10]},
  {"name": "Multiple Man", "img": "Images/Minis/xmrf007.jpg", "alt": "Multiple Man xmrf007", "keywords": ["Hydra", "Maggia", "S.H.I.E.L.D.", "X-Factor", "X-Men", "Detective", "Spy"], "points": [40, 10]},
  {"name": "Negasonic Teenage Warhead", "img": "Images/Minis/dxf041.jpg", "alt": "Negasonic Teenage Warhead dxf041", "keywords": ["Hellfire Club", "X-Men"], "points": [50]},
  {"name": "Nico Minoru", "img": "Images/Minis/swb045.jpg", "alt": "Nico Minoru swb045", "keywords": ["Runaways", "Mystical"], "points": [40]},
  {"name": "Nightwing and Batgirl", "img": "Images/Minis/bm100.jpg", "alt": "Nightwing and Batgirl bm100", "keywords": ["Batman Family", "Gotham City"], "points": [176]},
  {"name": "Peter Parker", "img": "Images/Minis/svc016.jpg", "alt": "Peter Parker svc016", "keywords": ["Avengers", "Codex", "Spider-Man Family", "Reporter", "Scientist"], "points": [35]},
  {"name": "Professor X", "img": "Images/Minis/xmrf028.jpg", "alt": "Professor X xmrf028", "keywords": ["Illuminati", "Shi'ar", "X-Men"], "points": [25]},
  {"name": "Prowler", "img": "Images/Minis/svc004.jpg", "alt": "Prowler svc004", "keywords": ["Spider-Man Family"], "points": [30]},
  {"name": "Proxima Midnight", "img": "Images/Minis/gotg050.jpg", "alt": "Proxima Midnight gotg050", "keywords": ["Black Order", "Minions of Thanos", "Warrior"], "points": [100]},
  {"name": "Rachel Summers", "img": "Images/Minis/wcr009.jpg", "alt": "Rachel Summers wcr009", "keywords": ["Excalibur", "Jean Grey School for Higher Learning", "Phoenix Force", "Starjammers", "X-Men", "Future"], "points": [50, 100]},
  {"name": "Rama Tut", "img": "Images/Minis/ffff045.jpg", "alt": "Rama Tut ffff045", "keywords": ["Latveria", "Deity", "Future", "Past", "Ruler"], "points": [50]},
  {"name": "Red Ghost", "img": "Images/Minis/ffff046.jpg", "alt": "Red Ghost ffff046", "keywords": ["Intelligencia", "Animal", "Scientist"], "points": [50]},
  {"name": "Sage", "img": "Images/Minis/hx008.jpg", "alt": "Sage hx008", "keywords": ["X-Force", "X-Men"], "points": [40]},
  {"name": "Scarlet Spider", "img": "Images/Minis/asm018.jpg", "alt": "Scarlet Spider asm018", "keywords": ["Brute", "Spider-Man Family"], "points": [77, 117]},
  {"name": "Scarlet Witch", "img": "Images/Minis/affe043.jpg", "alt": "Scarlet Witch affe043", "keywords": ["Avengers", "Brotherhood of Mutants", "X-Men", "Detective", "Mystical"], "points": [50]},
  {"name": "Sentinel", "img": "Images/Minis/xmrf008.jpg", "alt": "Sentinel xmrf008", "keywords": ["Sentinel", "Armor", "Robot"], "points": [25]},
  {"name": "Sinister Clone", "img": "Images/Minis/hx015.jpg", "alt": "Sinister Clone hx015", "keywords": ["Battleworld: Other", "Marauders", "Scientist"], "points": [20]},
  {"name": "Spiderling", "img": "Images/Minis/swb040.jpg", "alt": "Spiderling swb040", "keywords": ["Battleworld: Regency", "S.H.I.E.L.D.", "Spider-Man Family"], "points": [30]},
  {"name": "Spider-Man", "img": "Images/Minis/ffffff005.jpg", "alt": "Spider-Man ffffff005", "keywords": ["Fantastic Four", "Spider-Man Family", "Scientist"], "points": [50]},
  {"name": "Spider-Man", "img": "Images/Minis/svc001.jpg", "alt": "Spider-Man affe006", "keywords": ["Avengers", "Codex", "Spider-Man Family", "Reporter", "Scientist"], "points": [40]},
  {"name": "Spider-Man", "img": "Images/Minis/affe006.jpg", "alt": "Spider-Man affe006", "keywords": ["Fantastic Four", "Spider-Man Family", "Reporter", "Scientist"], "points": [65]},
  {"name": "Spider-Man", "img": "Images/Minis/eax015.jpg", "alt": "Spider-Man eax015", "keywords": ["Earth X", "Spider-Man Family", "Police", "Reporter"], "points": [30]},
  {"name": "Spider-Man", "img": "Images/Minis/svc018.jpg", "alt": "Spider-Man svc018", "keywords": ["Avengers", "Champions", "S.H.I.E.L.D.", "Spider-Man Family", "Ultimates"], "points": [65]},
  {"name": "Spider-Man", "img": "Images/Minis/swb018.jpg", "alt": "Spider-Man swb018", "keywords": ["Avengers", "Battleworld: Spider-Island", "Spider-Man Family", "Celebrity", "Ruler"], "points": [70]},
  {"name": "Spider-Man", "img": "Images/Minis/sfsm031.jpg", "alt": "Spider-Man sfsm031", "keywords": ["Avengers", "Spider-Man Family"], "points": [70]},
  {"name": "Spider-Man", "img": "Images/Minis/eax037a.jpg", "alt": "Spider-Man eax037a", "keywords": ["Avengers", "Spider-Man Family", "Reporter", "Scientist"], "points": [90, 96]},
  {"name": "Spider-Man", "img": "Images/Minis/wi101.jpg", "alt": "Spider-Man Wi101", "keywords": ["Avengers", "Marvel Knights", "Spider-Man Family", "Reporter", "Scientist"], "points": [50, 100]},
  {"name": "Spider-Man", "img": "Images/Minis/gg104.jpg", "alt": "Spider-Man gg 104", "keywords": ["Fantastic Four", "Scientist"], "points": [90]},
  {"name": "Spider-Woman", "img": "Images/Minis/eax053b.jpg", "alt": "Spider-Woman eax053b", "keywords": ["Loners", "Spider-Man Family", "Armor", "Mystical"], "points": [80]},
  {"name": "Spirit Spider", "img": "Images/Minis/svc061.jpg", "alt": "Spirit Spider svc061", "keywords": ["Spider-Man Family", "Mystical"], "points": [90]},
  {"name": "Stardust", "img": "Images/Minis/ffff048.jpg", "alt": "Stardust ffff048", "keywords": ["Cosmic", "Herald"], "points": [100]},
  {"name": "Storm", "img": "Images/Minis/uxm003.jpg", "alt": "Storm uxm003", "keywords": ["Deity", "Morlocks", "Ruler", "Utopia", "Wakanda", "X-Men"], "points": [50]},
  {"name": "Storm", "img": "Images/Minis/affe009.jpg", "alt": "Storm affe009", "keywords": ["Wakanda", "X-Men", "Deity", "Ruler"], "points": [35]},
  {"name": "Tempo", "img": "Images/Minis/xmrf045.jpg", "alt": "Tempo xmrf045", "keywords": ["Acolytes", "Marauders", "Utopia", "X-Men"], "points": [35]},
  {"name": "Unseen", "img": "Images/Minis/ai043.jpg", "alt": "Unseen ai043", "keywords": ["Cosmic", "Soldier", "Spy"], "points": [65]},
  {"name": "Valeria Richards", "img": "Images/Minis/f4027.jpg", "alt": "Valeria Richards ff027", "keywords": ["Fantastic Four", "Latveria", "Scientist"], "points": [40]},
  {"name": "Wolverine", "img": "Images/Minis/xmrf001.jpg", "alt": "Wolverine xmrf001", "keywords": ["Avengers", "Jean Grey School for Higher Learning", "Weapon X", "X-Men"], "points": [45]},
];
